{
  imports = [
    ./alacritty.nix
    ./anyrun
    ./dunst.nix
    ./eww
    ./eza.nix
    ./fastfetch.nix
    ./firefox.nix
    ./git.nix
    ./lazygit.nix
    ./mount.nix
    ./niri
    ./nixvim
    ./qt.nix
    ./spicetify.nix
    ./starship.nix
    ./stylix.nix
    ./swayidle.nix
    ./swaylock.nix
    ./tmux.nix
    ./wpaperd.nix
    ./xdg.nix
    ./yazi.nix
    ./zathura.nix
    ./zsh.nix
  ];
}
